version: "3.8"

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - redis
  celery:
    build: .
    command: python -m celery -A taxi worker -l INFO
    volumes:
      - .:/usr/src/app
    depends_on:
      - django
      - redis
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
